title: Kenny Wong Works
author: kennyhwong
email: kennyhwongatucladotedu
description: > # this means to ignore newlines until "baseurl:"
  This is my personal portfolio of graduate and professional work in the fields of Architecture and Urban & Regional Planning. I am currently based in Los Angeles, CA as the Assistant Director of Design Research at cityLAB UCLA, a research center in the Department of Architecture and Urban Design.

# social links
twitter_username: # your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  # your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
